#lang racket
(require "tag.rkt")
(require "get-put.rkt")
(require "number.rkt")
(require "polynomial.rkt")

(install-polynomial-package)
(define (make-poly o c)
	((get 'make 'polynomial) o c))
(provide make-poly)

(provide make-scheme-number)
(provide make-integer)
(provide make-real)
(provide make-rational)
(provide make-complex-from-real-imag)
(provide make-complex-from-mag-ang)
(provide add)
(provide sub)
(provide mul)
(provide numer)
(provide denom)
(provide real-part)
(provide imag-part)
(provide equ?)
(provide =zero?)
(provide raise)
(provide project)
(provide drop)
(provide apply-generic-powered)
