#lang racket

;;;get put;;;
(define global-array '())

(define (make-entry k v) (list k v))
(define (key entry) (car entry))
(define (value entry) (cadr entry))

(define (put-table table key1 key2 item)
	(if (not (hash-has-key? table key1))
		(hash-set! table key1 (make-hash))
		true)
	(hash-set! (hash-ref table key1) key2 item))

(define (get-table table key1 key2)
	(define (not-found . msg)
		;  (display msg (current-error-port))
		;  (display "\n")
		false)
	(if (hash-has-key? table key1)
		(if (hash-has-key? (hash-ref table key1) key2)
			(hash-ref (hash-ref table key1) key2)
			(not-found "Bad key -- KEY2" key2))
		(not-found "Bad key -- KEY1" key1)))

(define *op-table* (make-hash))
(define (put op type item)
	(put-table *op-table* op type item))
(define (get op type)
	(get-table *op-table* op type))

(define *coercion-table* (make-hash))
(define (put-coercion type1 type2 item)
	(put-table *coercion-table* type1 type2 item))
(define (get-coercion type1 type2)
	(get-table *coercion-table* type1 type2))

;;;tag;;;
(define (attach-tag type-tag contents)
	(cons type-tag contents))
(define (type-tag datum)
	(cond ((pair? datum) (car datum))
				((number? datum) 'scheme-number)
				(else (error "Bad tagged datum: TYPE-TAG" datum))))
(define (contents datum)
	(cond ((pair? datum) (cdr datum))
				((number? datum) datum)
				(else (error "Bad tagged datum: CONTENTS" datum))))

;;;generic;;;
(define (apply-generic op . args)
	(let ((type-tags (map type-tag args)))
		(let ((proc (get op type-tags))) 
			(if proc
				(apply proc (map contents args))
				(if (= (length args) 2)
					(let ((type1 (car type-tags)) 
								(type2 (cadr type-tags))
								(a1 (car args))
								(a2 (cadr args)))
						(let ((t1->t2 (get-coercion type1 type2))
									(t2->t1 (get-coercion type2 type1))) 
							(cond  ((eq? type1 type2)
											(if (t1->t2 a1 a2)
												(t1->t2 a1 a2)
												(error "No method for these types"
																		 (list op type-tags))))
										 (t1->t2 
											 (apply-generic op (t1->t2 a1) a2))
										 (t2->t1
											(apply-generic op a1 (t2->t1 a2))) 
										(else (error "No method for these types"
																 (list op type-tags))))))
					(error "No method for these types" (list op type-tags)))))))

;;;content;;;
(define (install-scheme-number-package)
	(define (tag x) (attach-tag 'scheme-number x))
	(put 'add '(scheme-number scheme-number)
			 (lambda (x y) (tag (+ x y))))
	(put 'sub '(scheme-number scheme-number)
			 (lambda (x y) (tag (- x y))))
	(put 'mul '(scheme-number scheme-number)
			 (lambda (x y) (tag (* x y))))
	(put 'div '(scheme-number scheme-number)
			 (lambda (x y) (tag (/ x y))))
	(put 'make 'scheme-number (lambda (x) (tag x)))
	(put '=zero? '(scheme-number) (lambda (x) (= x 0)))
	(put 'exp '(scheme-number scheme-number)
			 (lambda (x y) (tag (expt x y))))
	'done)
	
(define (install-rational-package)
	(define (number x) (car x))
	(define (denom x) (cdr x))
	(define (make-rat n d)
		(let ((g (gcd n d)))
			(cons (/ n g) (/ d g))))
	(define (add-rat x y)
		(make-rat (+ (* number x) (denom y)
								 (* (number y) (denom x)))
							(* (denom x) (denom y))))
	(define (sub-rat x y)
		(make-rat (- (* (number x) (denom y))
								 (* (number y) (denom x)))
							(* (denom x) (denom y))))
	(define (mul-rat x y)
		(make-rat (* (number x) (number y))
							(* (denom x) (denom y))))
	(define (div-rat x y)
		(make-rat (* (number x) (denom y))
							(* (denom x) (number y))))
	(define (=zero? x)
		(= (number x) 0))

	(define (tag x) (attach-tag 'rational x))
	(put 'number '(rational) number)
	(put 'denom '(rational) denom)
	(put 'add '(rational rational)
			 (lambda (x y) (tag (add-rat x y))))
	(put 'sub '(rational rational)
			 (lambda (x y) (tag (sub-rat x y))))
	(put 'mul '(rational rational)
			 (lambda (x y) (tag (mul-rat x y))))
	(put 'div '(rational rational)
			 (lambda (x y) (tag (div-rat x y))))
	(put 'make 'rational
			 (lambda (n d) (tag (make-rat n d))))
	(put '=zero? '(rational)
			 (lambda (x) (=zero? x)))
	'done)

(define (install-rectangular-package)
	; internal procedures
	(define (real-part z) (car z))
	(define (imag-part z) (cdr z))
	(define (make-from-real-imag x y) (cons x y))
	(define (square x) (* x x))
	(define (magnitude z)
		(sqrt (+ (square (real-part z))
						 (square (imag-part z)))))
	(define (angle z)
		(atan (imag-part z) (real-part z)))
	(define (make-from-mag-ang r a)
		(cons (* r (cos a)) (* r (sin a))))
	(define (=zero? z)
		(and (= (real-part z) 0)
				 (= (imag-part z) 0)))

	; interface to the rest of the system
	(define (tag x) (attach-tag 'rectangular x))
	(put 'real-part '(rectangular) real-part) 
	(put 'imag-part '(rectangular) imag-part)
	(put 'magnitude '(rectangular) magnitude)
	(put 'angle '(rectangular) angle)
	(put 'make-from-real-imag 'rectangular
			 (lambda (x y) (tag (make-from-real-imag x y))))
	(put 'make-from-mag-ang 'rectangular
			 (lambda (r a) (tag (make-from-mag-ang r a))))
	(put '=zero? '(rectagular) (lambda (z) (=zero? z)))
	'done)

(define (install-polar-package)
	;; internal procedures
	(define (magnitude z) (car z))
	(define (angle z) (cdr z))
	(define (make-from-mag-ang r a) (cons r a)) 
	(define (real-part z)
		(* (magnitude z) (cos (angle z)))) 
	(define (imag-part z)
		(* (magnitude z) (sin (angle z)))) 
	(define (square x) (* x x))
	(define (make-from-real-imag x y)
		(cons (sqrt (+ (square x) (square y)))
					(atan y x)))
	(define (=zero? z)
		(= 0 (magnitude z)))

	;; interface to the rest of the system
	(define (tag x) (attach-tag 'polar x))
	(put 'real-part '(polar) real-part)
	(put 'imag-part '(polar) imag-part)
	(put 'magnitude '(polar) magnitude)
	(put 'angle '(polar) angle)
	(put 'make-from-real-imag 'polar
			 (lambda (x y) (tag (make-from-real-imag x y))))
	(put 'make-from-mag-ang 'polar
			 (lambda (r a) (tag (make-from-mag-ang r a))))
	(put '=zero? '(polar) (lambda (z) (=zero? z)))
	'done)

(define (install-complex-package)
	(define (make-from-real-imag x y)
		((get 'make-from-real-imag 'rectangular) x y))	
	(define (make-from-mag-ang r a)
		((get 'make-from-mag-ang 'polar) r a))
	(define (real-part z) (apply-generic 'real-part z))
	(define (imag-part z) (apply-generic 'imag-part z))
	(define (magnitude z) (apply-generic 'magnitude z))
	(define (angle z) (apply-generic 'angle z))
	(define (=zero? z) (apply-generic '=zero? z))

	(define (add-complex z1 z2)
		(make-from-real-imag (+ (real-part z1) (real-part z2))
												 (+ (imag-part z1) (imag-part z2))))
	(define (sub-complex z1 z2)
		(make-from-real-imag (- (real-part z1) (real-part z2))
												 (- (imag-part z1) (imag-part z2))))
	(define (mul-complex z1 z2)
		(make-from-real-imag (* (magnitude z1) (magnitude z2))
												 (+ (angle z1) (angle z2))))
	(define (div-complex z1 z2)
		(make-from-real-imag (/ (magnitude z1) (magnitude z2))
												 (- (angle z1) (angle z2))))
	
	(define (tag z) (attach-tag 'complex z))
	(put 'add '(complex complex)
			 (lambda (z1 z2) (tag (add-complex z1 z2))))
	(put 'sub '(complex complex)
			 (lambda (z1 z2) (tag (sub-complex z1 z2))))
	(put 'mul '(complex complex)
			 (lambda (z1 z2) (tag (mul-complex z1 z2))))
	(put 'div '(complex complex)
			 (lambda (z1 z2) (tag (div-complex z1 z2))))
	(put 'make-from-real-imag 'complex
			 (lambda (x y) (tag (make-from-real-imag x y))))
	(put 'make-from-mag-ang 'complex
			 (lambda (r a) (tag (make-from-mag-ang r a))))
	(put 'real-part '(complex) real-part)
	(put 'imag-part '(complex) imag-part)
	(put 'magnitude '(complex) magnitude)
	(put 'angle '(complex) angle)
	(put '=zero? '(complex) =zero?)
	'done)

;;;coercion;;;
(define (scheme-number->complex n)
	(make-complex-from-real-imag (contents n) 0))
(put-coercion 'scheme-number 'complex scheme-number->complex)

(define (scheme-number->scheme-number n) n) 
(define (complex->complex z) z) 
(put-coercion 'scheme-number 'scheme-number scheme-number->scheme-number)
(put-coercion 'complex 'complex complex->complex)

;;;body;;;
(install-scheme-number-package)
(install-rational-package)
(install-polar-package)
(install-rectangular-package)
(install-complex-package)

(define (make-scheme-number n)
	((get 'make 'scheme-number) n))
(define (make-rational n d)
	((get 'make 'rational) n d))
(define (make-complex-from-real-imag x y)
	((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
	((get 'make-from-mag-ang 'complex) r a))

(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (number r) (apply-generic 'number r))
(define (denom r) (apply-generic 'denom r))
(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (=zero? x) (apply-generic '=zero? x))

(define (equ? a b)
	(let ((a-tag (type-tag a))
				(b-tag (type-tag b)))
		(cond ((and (eq? a-tag 'complex) (eq? b-tag 'complex))
					 (and (= (real-part a) (real-part b))
								(= (imag-part a) (imag-part b))))
					((and (eq? a-tag 'scheme-number) (eq? b-tag 'rational))
					 (and (= (contents a) (number b)) (= 1 (denom b))))
					((and (eq? b-tag 'scheme-number) (eq? a-tag 'rational))
					 (and (= (contents b) (number a)) (= 1 (denom a))))
					(else #f))))

(define a (make-scheme-number 3))
(define b (make-scheme-number 2))
(define z1 (make-complex-from-real-imag 1 1))
(define z2 (make-complex-from-real-imag 3 4))

(define (exp x y) (apply-generic 'exp x y))

; 81-a 
; (exp z1 z2)
; complex から complexに変換ができるため
; apply-generic内で、complex->complexがよばれ
; またapply-genericが評価され、またcomplexからcomplexへ型変換される

; 81-c
(exp a b)



